### ISSUE TITLE
The ThisNetWorks AdminTree feature is not available on the Feature tree

### ISSUE THREAD

**Issue by auditio** [ThisNetWorks/ThisNetWorks.OrchardCore.AdminTree#1]
I have followed the installation instructions and loaded ThisNetworks.OrchardCore.AdminTree module under src/OrcharCode.Modules. But I don't see the feature available on the tree to be able to enable it

**Comment by deanmarcussen** [comment]
Did you take a reference to the module from the `OrchardCore.Cms.Web` project?

**Comment by auditio** [comment]
That's what I was missing. Thank you!
