### ISSUE TITLE
Update to latest OrchardCore

### ISSUE THREAD

**Issue by deanmarcussen** [ThisNetWorks/ThisNetWorks.OrchardCore.AdminTree#2]
Now that the tags and display drivers pr is merged to OrchardCore the registration for the display drivers needs to be updated

**Comment by auditio** [comment]
Hey @deanmarcussen, 

It is documented that this module is intended to be build using the Orchard Core dev/deanmarcussen/tags branch, is that still true? I cannot find that particular branch

**Comment by deanmarcussen** [comment]
Yes, the tags branch has been merged, so I have updated this to the latest
